[package]
name = "near-self-update-model"
version = "0.1.0"
edition = "2021"

[lib]
name = "near_self_update_model"

[dependencies]
anyhow = { workspace = true }
near-sdk = { workspace = true }
async-trait = { workspace = true }
integration-trait = { workspace = true }
